#!/bin/bash

input_dir="$1"
input_file=$(basename "${input_dir%.*}")
output_file="../output/${input_file}_nn_list.csv"

awk 'NR==5 { print }' "$input_dir" >> "$output_file"
awk 'NR==6 { print }' "$input_dir" >> "$output_file"
awk 'NR==18 { print }' "$input_dir" >> "$output_file"
awk 'NR==19 { print }' "$input_dir" >> "$output_file"
awk 'NR==30 { print }' "$input_dir" >> "$output_file"
awk 'NR==25 { print }' "$input_dir" >> "$output_file"
awk 'NR==35 { print }' "$input_dir" >> "$output_file"
awk 'NR==40 { print }' "$input_dir" >> "$output_file"
awk 'NR==44 { print }' "$input_dir" >> "$output_file"
awk 'NR==48 { print }' "$input_dir" >> "$output_file"
awk 'NR==52 { print }' "$input_dir" >> "$output_file"
awk 'NR==56 { print }' "$input_dir" >> "$output_file"
awk 'NR==59 { print }' "$input_dir" >> "$output_file"
awk 'NR==62 { print }' "$input_dir" >> "$output_file"
awk 'NR==65 { print }' "$input_dir" >> "$output_file"
awk 'NR==68 { print }' "$input_dir" >> "$output_file"
awk 'NR==39 { print }' "$input_dir" >> "$output_file"
awk 'NR==72 { print }' "$input_dir" >> "$output_file"
awk 'NR==335 { print }' "$input_dir" >> "$output_file"
awk 'NR==336 { print }' "$input_dir" >> "$output_file"
awk 'NR==352 { print }' "$input_dir" >> "$output_file"
awk 'NR==353 { print }' "$input_dir" >> "$output_file"
awk 'NR==369 { print }' "$input_dir" >> "$output_file"
awk 'NR==364 { print }' "$input_dir" >> "$output_file"
awk 'NR==80 { print }' "$input_dir" >> "$output_file"
awk 'NR==85 { print }' "$input_dir" >> "$output_file"
awk 'NR==95 { print }' "$input_dir" >> "$output_file"
awk 'NR==99 { print }' "$input_dir" >> "$output_file"
awk 'NR==109 { print }' "$input_dir" >> "$output_file"
awk 'NR==113 { print }' "$input_dir" >> "$output_file"
awk 'NR==122 { print }' "$input_dir" >> "$output_file"
awk 'NR==125 { print }' "$input_dir" >> "$output_file"
awk 'NR==134 { print }' "$input_dir" >> "$output_file"
awk 'NR==137 { print }' "$input_dir" >> "$output_file"
awk 'NR==84 { print }' "$input_dir" >> "$output_file"
awk 'NR==147 { print }' "$input_dir" >> "$output_file"
awk 'NR==158 { print }' "$input_dir" >> "$output_file"
awk 'NR==159 { print }' "$input_dir" >> "$output_file"
awk 'NR==168 { print }' "$input_dir" >> "$output_file"
awk 'NR==169 { print }' "$input_dir" >> "$output_file"
awk 'NR==177 { print }' "$input_dir" >> "$output_file"
awk 'NR==172 { print }' "$input_dir" >> "$output_file"
awk 'NR==179 { print }' "$input_dir" >> "$output_file"
awk 'NR==208 { print }' "$input_dir" >> "$output_file"
awk 'NR==185 { print }' "$input_dir" >> "$output_file"
awk 'NR==209 { print }' "$input_dir" >> "$output_file"
awk 'NR==190 { print }' "$input_dir" >> "$output_file"
awk 'NR==225 { print }' "$input_dir" >> "$output_file"
awk 'NR==194 { print }' "$input_dir" >> "$output_file"
awk 'NR==226 { print }' "$input_dir" >> "$output_file"
awk 'NR==197 { print }' "$input_dir" >> "$output_file"
awk 'NR==242 { print }' "$input_dir" >> "$output_file"
awk 'NR==183 { print }' "$input_dir" >> "$output_file"
awk 'NR==243 { print }' "$input_dir" >> "$output_file"